# Generated by Django 4.2.2 on 2023-07-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prices',
        ),
    ]
